Financial-Times/o-ads

README.md

Addresses my last comment in #8.

Update documentation to describe how to instantiate from o-autoinit

---

circle.yml
test/qunit/gpt.test.js

…tion is sufficient
/cc @leggsimon @adgad @andrewgeorgiou1981

Remove unnecessary assertion

---

README.md
docs/SLOT_CONFIG_REFERENCE.md
test/qunit/slots.test.js

/cc @adgad @andrewgeorgiou1981 
Updated docs to clarify how to initialise the library as well as a more detailed reference to possible slot / library configurations.
Have a look and let me know if anything is missing or something is unclear.
Also please verify the details about the responsive sizes and formats are correct.

Documentation and examples

---

.gitignore
circle.yml
package.json
test/browser/nightwatch.json
test/browser/tests/demos.js

Adding browser test (currently only one) to our CI
/cc @adgad

Nightwatch tests

---

src/js/ad-servers/gpt.js
src/js/slots.js
src/js/targeting.js
test/qunit/slots.test.js
test/qunit/targeting.test.js

/cc @VladDubrovskis @andrewgeorgiou1981 
Pass the responsive breakpoint to DFP to target.

Send the responsive breakpoint for targeting

---

src/js/slots.js

/cc @VladDubrovskis 
Turns out it was needed. Will fix coverage later.

Revert "Remove unneeded safety check"

---

test/qunit/mocks/gpt-mock.js
test/qunit/slots.test.js

/cc @VladDubrovskis 
Add test to cover case when size is false (i.e. no ad loaded)

Test for no size present

---

src/js/slots.js
test/qunit/slots.test.js

/cc @VladDubrovskis @leggsimon @andrewgeorgiou1981

Fix data-o-ads-loaded when format has multiple sizes

---

test/browser/tests/individual-ad-with-custom-targeting-values.js
test/browser/tests/individual-ad.js
test/browser/tests/master-and-companion.js
test/browser/tests/responsive-positions.js

/cc @adgad @leggsimon @andrewgeorgiou1981

add more browser tests for demo pages

---

demos/src/config.json
demos/src/individual.mustache
docs/DATA_PROVIDERS.md
karma.conf.js
main.js
src/js/data-providers/moat.js
test/qunit/moat.test.js

@adgad @VladDubrovskis @andrewgeorgiou1981

Moat integration

---

src/js/slot.js
src/js/slots.js
src/js/utils/events.js
test/qunit/slots.post.message.test.js
test/qunit/slots.test.js

/cc @andrewgeorgiou1981 @VladDubrovskis @leggsimon

Master and Companion ads cant lazy load

---

docs/SLOT_CONFIG_REFERENCE.md
src/js/slot.js
src/js/slots.js
test/qunit/slots.post.message.test.js

/cc @adgad @leggsimon @andrewgeorgiou1981

Swipe config for o ads embed

---

demos/src/demo.scss
main.scss
src/scss/base.scss

@andrewgeorgiou1981 @ironsidevsquincy

Implement silent mode

---

bower.json
src/js/utils/responsive.js
test/qunit/helpers.js

/cc @andrewgeorgiou1981 @leggsimon @adgad

Responsive ads and scrollbar

---

src/js/ad-servers/gpt.js
test/qunit/gpt.test.js

/cc @andrewgeorgiou1981 @VladDubrovskis @rowanbeentje 
(Will do a v3.5.3 release off this branch, and do another commit into master to also remove.

Remove resizing of iframe to fix web app full page

---

src/js/ad-servers/gpt.js
test/qunit/gpt.test.js

Same PR as before, but into master.
@VladDubrovskis @andrewgeorgiou1981 @leggsimon

Remove resizing of iframes

---

src/js/slot.js
test/qunit/slots.test.js

/cc @VladDubrovskis @andrewgeorgiou1981 
Will do a separate PR to review/update docs

Lazy loading as a global config option

---

src/js/utils/index.js

@VladDubrovskis @andrewgeorgiou1981

Don't execute the error callback

---

src/js/slots.js
test/qunit/slots.test.js

/cc @andrewgeorgiou1981 @VladDubrovskis

Refresh responsive if the slot goes to false

---

src/js/slots.js
test/qunit/slots.post.message.test.js
test/qunit/utils.test.js

/cc @leggsimon @andrewgeorgiou1981 @adgad @rowanbeentje 
A copy of https://github.com/Financial-Times/o-ads/pull/39
I think there is something that does not click in the pipeline if a PR is coming from a forked repo

merge Rowans patch

---

src/js/slot.js
test/browser/extended/responsive-positions.js
test/qunit/slots.responsive.test.js

/cc @VladDubrovskis @andrewgeorgiou1981

Clear the existing ad if going from ad to false

---

docs/SLOT_CONFIG_REFERENCE.md
src/js/slot.js
test/qunit/slots.test.js

/cc @andrewgeorgiou1981 @aintgoin2goa

Allow fluid as a size

---

src/js/slot.js
src/js/slots.js
test/browser/nightwatch.json
test/qunit/slots.test.js

/cc @andrewgeorgiou1981 
Previously, if two ads were in view they could have triggered in the wrong order. This meant that some master/companion campaigns wouldn't load. Change to have a single Observer, and manipulate the changes to be in the right order.

Single observer

---

docs/SLOT_CONFIG_REFERENCE.md
karma.conf.js
package.json
src/js/slot.js
src/js/slots.js
test/qunit/slots.test.js

/cc @adgad @andrewgeorgiou1981

Fix threshold config property

---

README.md
main.js
test/qunit/main.test.js

@andrewgeorgiou1981 @VladDubrovskis

Emit an event once initialised

---

main.scss
src/scss/base.scss

followed up on consistency with transition animation

updated transition

---

main.js
test/qunit/api.test.js

Fix firefox ads and write test

User data fix

---

docs/docs/developer-guide/advanced-display.md
src/js/slot.js
src/js/utils/events.js
test/qunit/slots.test.js

/cc @adgad @andrewgeorgiou1981 @gvonkoss 
related to: https://github.com/Financial-Times/n-ui/pull/552

add oAds.collapse event

---

src/js/data-providers/krux.js
test/browser/extended/responsive-positions.js
test/qunit/krux.test.js

@VladDubrovskis @gvonkoss @andrewgeorgiou1981

Send krux attrs even if no config attrs

---

main.scss

/cc @adgad @gvonkoss @andrewgeorgiou1981

change the background color

---

circle.yml
package.json
test/browser/basic/individual-ad-with-custom-targeting-values.js
test/browser/basic/individual-ad.js
test/browser/extended/individual-ad-lazy-load-margin.js
test/browser/extended/individual-ad-lazy-load.js
test/browser/extended/master-and-companion.js
test/browser/extended/responsive-ad.js
test/browser/extended/responsive-positions.js
test/browser/nightwatch-globals.js
test/browser/nightwatch.json

AS far as i got with making tests stable. Not much has changed as the instability is not consistent at all, usually things break on the SauceLabs side.
Added the globals file so should be easy to maintain and tweak in the future, plus added the `--suiteRetries` flag that should retry the failed tests 3 times.
/cc @adgad @andrewgeorgiou1981 @gvonkoss

More stable browser tests

---

main.scss

Use o-colors palette function. Resolves #91

Fix background styles

---

src/js/utils/index.js
test/qunit/config.test.js

/cc @adgad @gvonkoss @andrewgeorgiou1981 @kavanagh 
A fix for the IE + polyfill issue

O ads and the case of breaking ie

---

circle.yml
src/js/ad-servers/gpt.js

new custom event for googletag.display() called on slot

---

package.json
secret-squirrel.js
test/fixtures/user-api-response.json
test/qunit/api.test.js

and I also have changed user id for tests. The id wouldn't be able to access private information but we decide to change it in case.

install secret-squirrel

---

README.md
bower.json
main.scss

this should be a new major version

update to new major versions of o-colors and o-visual-effects

---

main.js
main.scss
src/js/config.js
src/js/slot.js
src/js/slots.js
src/scss/base.scss

Adds a label with border, however preserves the existing functionality so that we don't break anything.

AT-2106: Added a consistent way to add a label with borders

---

.eslintignore
src/.eslintrc.json
test/.eslintrc.json

- Excluding compiled demos from linting
- Removing the need to have consistent JSDoc rules in this repo (_since it brings unnecessary work to fix them at the moment, taken into account that this project is not making use of JSDoc to generate documentation_)
-  Adding specific eslint rules for test code

Remove noise from linting results

---

.eslintignore
karma.conf.js
main.js
src/.eslintrc.json
src/js/ad-servers/gpt.js
src/js/data-providers/krux.js
src/js/data-providers/moat.js
src/js/slot.js
src/js/slots.js
src/js/targeting.js
src/js/utils/index.js
src/js/utils/log.js
test/.eslintrc.json
test/browser/config/nightwatch-globals.js
test/browser/config/nightwatch-local.js
test/browser/config/nightwatch.conf.js
test/browser/extended/responsive-ad.js
test/qunit/api.test.js
test/qunit/config.test.js
test/qunit/gpt.test.js
test/qunit/helpers.js
test/qunit/main.test.js
test/qunit/mocks/gpt-mock.js
test/qunit/slots.post.message.test.js
test/qunit/slots.test.js
test/qunit/targeting.test.js

Fix broken integration tests
Temporarily reduced number of nightwatch workers
Removed linting errors from nightwatch files
Ignoring nightwatch-local when linting

"Fixed" most linting errors

---

.eslintrc-complexity.js
package.json

Added a new (totally optional) task for checking code complexity in addition to all other linting rules

Added new lint-complexity task

---

.eslintignore

Already proposed this one, was reverted mistakenly

remove build files from eslint

---

docs/docs/developer-guide/advanced-display.md
docs/docs/developer-guide/display.md
docs/docs/developer-guide/new-product.md
main.js

Fixes #170 - Improved documentation and made `initAll` a public method

---

docs/docs/developer-guide/display.md

This is the bit of code that I am basing this bit of documentation on: https://github.com/Financial-Times/o-ads/blob/master/src/js/slot.js#L315

Fixes #105 - Add documentation about "name" parameter

---

.circleci/config.yml
package-lock.json
package.json

This adds `bundlesize` (a package for checking that file sizes stay within specified "budget" limits) so that we avoid increasing the size of the build assets excessively.
The build and the check run on CircleCI and the result is notified to GitHub so that the PR will not mergeable if the limits have been exceeded.

Added test-size task

---

.circleci/config.yml
.eslintignore
package.json

Remove snyk dependency

---

karma.conf.js
main.js
package.json
src/js/ad-servers/gpt.js
src/js/config.js
src/js/data-providers/api.js
src/js/data-providers/krux.js
src/js/data-providers/moat.js
src/js/slot.js
src/js/slots.js
src/js/targeting.js
src/js/utils/events.js
src/js/utils/index.js
src/js/utils/log.js
src/js/utils/messenger.js
src/js/utils/responsive.js
test/qunit/config.test.js
test/qunit/helpers.js
test/qunit/krux.test.js
test/qunit/mocks/gpt-mock.js
test/qunit/setup.js
test/qunit/setup.test.js
test/qunit/slots.test.js
test/qunit/targeting.test.js
test/qunit/utils.events.test.js
test/qunit/utils.test.js

This reverts commit 422e9702e01cee5e0449057381a0e586fcbfbe4e.

Revert "Upgrade all CJS to ESM (#227)"

---

karma.conf.js
main.js
package.json
src/js/ad-servers/gpt.js
src/js/config.js
src/js/data-providers/api.js
src/js/data-providers/krux.js
src/js/data-providers/moat.js
src/js/slot.js
src/js/slots.js
src/js/targeting.js
src/js/utils/events.js
src/js/utils/index.js
src/js/utils/log.js
src/js/utils/messenger.js
src/js/utils/responsive.js
test/cypress/support/index.js
test/qunit/config.test.js
test/qunit/helpers.js
test/qunit/krux.test.js
test/qunit/mocks/gpt-mock.js
test/qunit/setup.js
test/qunit/setup.test.js
test/qunit/slots.test.js
test/qunit/targeting.test.js
test/qunit/utils.events.test.js
test/qunit/utils.test.js

Revert changes including migration to esm and also reverting import statements to require

Hotfix esm

---

src/js/ad-servers/gpt.js

Depreciation notice message for `updateCorrelator`
More info here: https://support.google.com/admanager/answer/183281?hl=en

depreciation notice message for updateCorrelator

---

package.json
src/js/data-providers/krux.js
test/qunit/krux.test.js

This adds new krux-specific events that will enable new krux-related metrics which are currently impossible to gather.

Added new krux-specific events

---

demos/src/infinitescrolling.mustache
origami.json
secret-squirrel.js

Currently, the demo emulates infinite scrolling. Clicking the button `More Content`, some new dynamic fake content is added to the document together with a new Ad slot.

Add demo for infinite scrolling using button

---

main.js

Add behavioral and programmatic consent events

add consent events

---

src/js/utils/index.js

I initially got the probability wrong :)

Fix typo in metrics sampling

---

src/js/ad-servers/gpt.js
test/nightwatch/extended/responsive-positions.js
test/qunit/gpt.test.js

Updating the GPT Url based on this article: https://support.google.com/admanager/answer/179039

Update GPT url

---

karma.conf.js
package-lock.json
package.json
src/.eslintrc.json
test/.eslintrc.json

Updating some dependencies to their latest version

Updated some devDependencies

---

package.json
src/js/ad-servers/gpt.js

* loggedIn missing from GPT targeting as next-ads-api returns a boolean

Stringify all values passed in to GPT targeting

---

main.scss
secret-squirrel.js

* Added CSS rule to counter GPT broken CSS

Added CSS rule to counter GPT broken CSS (#311)

---

README.md

Migration guide update for v14

Migration guide update for v14

---

docs/_layouts/default.html
docs/docs/developer-guide/dfp-ad-unit.md
secret-squirrel.js

Add a section _Setting up the Ad Unit_ to building documentation.
- Jira issue [ADSDEV-304](https://financialtimes.atlassian.net/browse/ADSDEV-304?atlOrigin=eyJpIjoiYmU1NjUzZjIwYzA1NGVlNDk1YzNmZjlmZjEwMjc4NDciLCJwIjoiaiJ9)

ADSDEV-304 Add section describing Setting up the Ad Unit to building docs

---

.github/settings.yml

Snyk have changed the names of their github checks, which has broken our pipeline. This should fix it.

Fix Snyk config

---

README.md
demos/src/nativelazyloading.mustache
origami.json
secret-squirrel.js
src/js/ad-servers/gpt.js
test/jest/gpt.js
test/jest/testUtils/GoogleTagMock.js
test/qunit/gpt.test.js
test/qunit/mocks/gpt-mock.js

[ADSDEV-310](https://financialtimes.atlassian.net/browse/ADSDEV-310)
Adds GPT Lazy Load functionality.
```
gpt.enableLazyLoad` *(optional)* <Object> - GPT Lazy Load, where configuration parameters allow customization of lazy loading behaviour.
```

ADSDEV-310 GPT Lazy Loading demo

---

package.json
test/qunit/main.test.js

Remove unused dependency `fetch-mock`.

AdsTechRota: Remove unused dependency `fetch-mock`

---

package-lock.json
package.json

Downgrade jest, which errors when trying to import o-viewport. 
Not to merge yet, we might look to fix it for v26 rather than just downgrading jest

Downgrade jest

---

README.md

Fixes https://github.com/Financial-Times/o-ads/issues/326

Update README with info about collapsing ad slots

---

.github/settings.yml
.github/workflows/auto-approve.yml
MIGRATION.md
README.md
docs/docs/developer-guide/dfp-ad-unit.md
docs/docs/managing-consent.md

Part of [this ticket](https://financialtimes.atlassian.net/browse/ADSDEV-791)

replacing master to main

---

README.md

updating where the circleci icon is read

added circle token
