- docs/SLOT_CONFIG_REFERENCE.md
- src/js/slot.js
- src/js/slots.js
- test/qunit/mocks/gpt-mock.js
- test/qunit/slots.test.js
/cc @VladDubrovskis @andrewgeorgiou1981 (ADS-754)
Adds a data attribute to the element with the name of the format loaded e.g. `data-o-ads-loaded="Responsive"`.
This is so we can target that in CSS and give e.g. different padding to responsive creatives.
> Adds the ad format loaded to the slot as an attribute (ADS-754)

- src/js/ad-servers/gpt.js
- test/qunit/gpt.test.js
Not sure if there's a nicer way of doing it, but this fixes ads getting cut off when resized because the iframe has the original width/height as inline styles.
@VladDubrovskis @andrewgeorgiou1981 @leggsimon
> Fix for ads getting cut off when resized

- src/scss/base.scss
Hunch that this might be breaking the label in IE9 @VladDubrovskis @leggsimon
> Use px for label font

- src/js/utils/messenger.js
...improving JSON.parse overhead and avoid triggering try/catch debuggers.
@VladDubrovskis - I could have sworn I saw something like this elsewhere in the ads codebase already? Can't find it now though...
There's a lot of actual objects and random horribleness coming in messages from ads, tripping the debugger every frame if it's in all-errors mode, so this will silence some noise.
> Skip JSON.parse for things that don't look like stringified JSON objects

- src/js/slots.js
@adgad 
@VladDubrovskis 
@andrewgeorgiou1981 
Maybe a little messy, but rather than send the event in `o-ads-embed` I thought we could send it on its `whoami` event.
If we are considering any other metrics maybe we should extract the `sendAdLoadedTrackingEvent` function into its own module? _(Or maybe I should do that anyway 😬 ? )_
I wonder whether we could also get the creative size to send with this event.
(Haha italic emoji!)
> Add adsIframeLoad metric

- demos/src/individualcustomtargeting.mustache
- docs/DATA_PROVIDERS.md
- src/js/data-providers/krux.js
- test/qunit/krux.test.js
/cc @VladDubrovskis @andrewgeorgiou1981 @rowanbeentje 
If Krux executes before the ad loads, it takes up valuable time on the main thread. This PR delays the loading of Krux's script by a second, and also uses requestIdleCallback if available to wait for the user to be done interacting.
Before:
After:
> Delay the loading of the Krux JS

- src/js/slot.js
- src/js/slots.js
- test/browser/basic/individual-ad-with-custom-targeting-values.js
- test/browser/basic/individual-ad.js
- test/browser/extended/responsive-positions.js
- test/qunit/slots.responsive.test.js
- test/qunit/slots.test.js
/cc @VladDubrovskis @andrewgeorgiou1981  
Hopefully fixes most of the resizing issues, by making the logic a little clearer and more precise.
Note: moved responsive tests out into their own file as slots.test.js was getting huge.
> Fix resizing behaviour with responsive ads

- main.js
- test/qunit/main.test.js
- test/qunit/setup.js
Started looking at this code due to a problem where o-autoinit as part of a lazy-loaded comments setup was calling DOMContentLoaded again; this caused the already-initialised o-ads instance to reinitialise itself and wipe out any existing config.
Looking at the existing logic, the previous DOMContentLoaded event listener was added to document but removed from document.documentElement, so it could get triggered multiple times. Fixing that caused test failures because of some magic global state in the test runs, so I've also moved the event handling setup to within the constructor, and moved teardown to part of init; this ensures that in normal usage, init() will only be called once unless there are multiple explicit external calls.
> Improve initialisation logic with multiple DOMContentLoaded calls

- src/js/data-providers/krux.js
Krux does some weird thing where it downloads all it's URLs twice. Most of these are the same file so will be cache hits - but the controltag URL it downloads the second time is the newer one.
This updates the URL we use to the newer one, so that the second hit is a cache hit.
> Update Krux URL to newer one

- src/js/targeting.js
- test/qunit/targeting.test.js
@VladDubrovskis @andrewgeorgiou1981 @gvonkoss 
Some site's referers have their PII data in query strings, so don't send it (we still send socref, which seems like it's why they needed referers in the first place - and it's also sent _somewhere_ in the GPT call.
> Remove referrer targeting k/v

- docs/_layouts/default.html
- docs/docs/developer-guide/new-product.md
- main.js
- src/js/ad-servers/gpt.js
- src/js/data-providers/api.js
- src/js/data-providers/krux.js
- src/js/targeting.js
- test/fixtures/another-content-api-response.json
- test/fixtures/user-api-anonymous-response.json
- test/qunit/api.test.js
- test/qunit/gpt.test.js
- test/qunit/helpers.js
- test/qunit/krux.test.js
- test/qunit/main.test.js
@andrewgeorgiou1981 @rowanbeentje @gvonkoss 
Pretty beefy PR so would appreciate some scrutiny.
The gist is that it exposes an `updateContext` method on oAds, that will allow the web app to handle page swipes, log in/out and reset all the targeting data. This will also drop a new Krux pixel when the targeting has been updated (which should eliminate the need for the web-app to manually do a Krux('page:view')
(Caveat: haven't done any manual testing yet 😬 )
> Expose the ads api updating method for single page apps

- src/js/ad-servers/gpt.js
Setting these attributes on the o-ads container was not enough, they need to be on the iframe for screen readers and other assistive tech to really skip them
Would this catch all ads on the site, though?
@adgad @GlynnPhillips
> hide ads from screen readers

- src/js/ad-servers/gpt.js
Gets rid of our last remaining `pa11y` error http://a11y.ft.com/58468e2d585a081100d9051a
Ads are hidden from screen readers, so afaik this won't be read out to any end users. It's more for strict compliance with WCAG2.0, follows their recommendation in https://www.w3.org/TR/WCAG20-TECHS/H64.html, and ensures anyone who wants to run an audit of our site will see a nice, clean `0 Errors`.
> Add title to ad iFrame

- src/js/data-providers/api.js
- src/js/data-providers/krux.js
- test/qunit/api.test.js
- test/qunit/krux.test.js
- Ability to reset only specific Krux attributes (eg. page)
- Ability to set a custom timeout for getPageData request to ads-api
> Changes required to implement page level targeting on webapp

- src/js/ad-servers/gpt.js
- test/qunit/gpt.test.js
in the updateTargeting() function we over write existing values with new ones passed in. However existing values with no new values retain the existing value.
But the desired behaviour is to remove the keys / values not in the new set passed in to the update.
This PR implements the clearTargeting() function before setting the new keys / values.
> Amend: clear targeting before updating

- src/js/ad-servers/gpt.js
Fix for this issue;
https://trello.com/c/xikmgrcY/146-all-targeting-except-res-are-missing-when-resizing-browser-in-all-pages
Introduced when implementing page targeting for webApp, we cleared existing values before updating so attributes that were to be removed would be.
However when passing in an override object we should not clear the existing values and just add the new ones.
> Fix: dont clear gpt targeting when overriding

- src/js/ad-servers/gpt.js
@fenglish @rowanbeentje 
bug fix - pubads().clearTargeting was being called incorrectly and called before pubads lib loaded
> bug fix - pubads().clearTargeting was being called incorrectly 

- main.js
- test/qunit/api.test.js
- test/qunit/main.test.js
Commas in cookie values aren't allowed by the cookie spec, so in theory various special characters should be URL (percent) encoded in cookies.  FTConsent will be changing to always be encoded; this change will support that (but will otherwise be backwards compatible)
> Handle encoded ftconsent cookies

- src/scss/base.scss
When 250px of header height is reserved, and a small ad is rendered, instead of rendering it in the middle, render it at the bottom.
To my knowledge, the reserving 250px of header height is not currently in use. We're hoping to use this when we attempt to de-janky the page & retain current ad viewability levels.
> Better header ad viewability when small ad is rendered in larger space

- docs/docs/developer-guide/display.md
- main.scss
New options...
* `.o-ads--slate-background`
This is the same as `.o-ads--background` except that the background is slate (almost black).
* `.o-ads--placeholder`
This displays a backgound image (currently an ellipsis) to give the user a clear indication that something will be loaded in this place.
> Slate and placeholder options

- src/js/utils/index.js
iframes is only used within the iframeToSlotName function. Moving the iframes variable to be within the iframeToSlotName function means that the file will no longer try to read DOM upon being imported, this will help consumers of the module who are trying to use it in a server context where this is no DOM present such as Node.JS
> Avoid side-effects of reading the DOM upon being imported/required

- docs/Gemfile.lock
- docs/_config.yml
- docs/docs/developer-guide/advanced-display.md
- src/js/ad-servers/gpt.js
- src/js/slot.js
- test/qunit/gpt.test.js
In a few words, this update changes the way we set up collapsing of ads on o-ads.
From `true` / `false` to `before`, `never` and `after`
Context: There are three behaviours for ad slots when fetching ads.
1) Initially have the ad slot collapsed until an ad in found (`before`)
2) Initially have the ad slot extended, collapse it if no ad is found (`after`)
3) Never collapse the ad slot, even if no ad is found for it (`never`)
This change intends to make it simpler to have control over this behavior globally or per specific ad slot
- **breaking** Change the default collapse mode to `never`. The reason for that is that it's the default that google dfp uses
- **breaking** Change the page level option in oAdsOption to root level. e.g: 
```
// before
oAds.config({
collapseEmpty: `before`,
gpt: { …
```
> [BREAKING CHANGES] Update ads collapse config options

- package-lock.json
- package.json
Fix the vulnerabilities that can be fixed automatically by running `npm audit fix` (allegedly, the ones that are safe to fix).
> Fix easy-to-fix npm dependencies vulnerabilities

- origami.json
Removing the 'responsive-ad' origami demo temporarily as it's broken and it makes harder to debug other broken demo ('responsive-positions')
> Removed broken reponsive ad demo

- .eslintignore
Remove noisy test output when pushing.
Eslint was running against built files
> fix: ignore build files in eslint

- main.js
- src/js/utils/log.js
which should fix this error:
https://sentry.io/nextftcom/ft-next-article/issues/692313407/?query=is:unresolved%20ads
... and added defensive code for `localStorage` being undefined on certain devices:
https://sentry.io/nextftcom/ft-next-article/issues/594124052/?query=is:unresolved%20ads
> Fix missing return value in error handler

- src/js/data-providers/krux.js
This should fix this error. Although it's difficult to test as it requires specific Android browsers: https://sentry.io/nextftcom/ft-next-article/issues/692583869/
> Added defensive code for browsers not supporting localStorage

- .circleci/config.yml
- .snyk
- package-lock.json
- package.json
This adds an additional check to our CircleCI pipeline looking for vulnerabilities on our dependencies.
It turns out that Snyk doesn't check for vulnerabilities on `devDependencies` by default and, since we have no non-dev dependencies at the moment, it has nothing to check 😜 . However, if we ever add any dependencies in the future, we will already be covered.
I have decided not to check devDependencies as I see no good reason at the moment to do so.
There are two remaining bits of work with regards to Snyk in `o-ads`:
1) We can ask Snyk to automatically create PRs to patch our vulnerabilities here
2) Since `o-ads` is a public repo, we can have Snyk directly checking our PRs (instead of running it on CircleCI).
both of them require Snyk/GitHub integrationand I am still waiting for an …
> Added snyk dependency and snyk-test task to CircleCI

- .circleci/config.yml
- .eslintignore
- package.json
Running Snyk on CIrcleCI is no longer necessary since it can now run as a GitHub status check
> Remove snyk check on CircleCI

- package.json
- test/browser/config/nightwatch.conf.js
I am temporarily disabling tests on Firefox since Browserstack is having issues with them. I will make sure to bring them back (or find a better solution) before we release a new version of `o-ads`.
> Temporarily disable failing Firefox tests

- src/js/ad-servers/gpt.js
GPT provides a "renderEnded" event which fires when the ad's creative code is injected into a slot.
o-ads listens for this event and then attempts to update the iFrame of the slot.
A recent issue surfaced, where it appears that if no ad creative is returned from dfp, the iFrame was not being created. 
This appears to be a bug with GPT; however it highlighted the need to be more robust in our coding.
Specifically we will now check for the presence of the iFrame before attempting to access its properties.
> Fix, check that iFrame exists before attempting to access/update it

- src/js/slots.js
- test/qunit/slots.post.message.test.js
Ideally the `o-ads-embed` script is wrapped around the creative one time. However, I found examples of ads where the creative includes an iframe within an iframe, which is also calling `o-ads-embed`. 
```
browser window
-->  iframe1 window
--> o-ads-embed.js
--> iframe2 window
--> o-ads-embed.js
--> creative.png
```
`o-ads-embed` sends a postMessage to `o-ads` on the main page, on the `document.load` event of the iframe. In this case, two postMessages will be sent to `o-ads`. One from the top level iframe and the second from iframe2 (in diagram above). They will both be picked up by `o-ads`, which will try and find an ad slot in the parent window. This will work for the first` o-ads-embed`, but not the second. 
For some reason, even though we do not detect an ad slot on the second call, …
> Don't send a postMessage if slot is undefined

- package-lock.json
- package.json
- test/cypress/integration/ad-requests.test.js
Removed the `ad` property check for value, as it changes quite often based on downstream APIs. It's good enough to check that the property is present.
> Fix failing tests on master

- src/js/slots.js
- test/qunit/slots.post.message.test.js
o-ads-embed has been upgraded to v3 successfully. FT.com is the only user so we can safely remove the backwards compatibility now and tidy up.
> Remove backwards compatibility with o-ads-embed v2

- src/js/data-providers/krux.js
- test/qunit/krux.test.js
Reverting the changes made in this commit: https://github.com/Financial-Times/o-ads/commit/6e9ef0246650007bed7809255976b7d6bc842734 as:
1. The approach to monitoring krux was not correct
2. We are in the process of replacing krux with permutive
> Removed unused krux monitoring events

- src/js/data-providers/moat.js
- test/qunit/main.test.js
This adds a new CustomEvent that enables monitoring when Moat IVT has timed out
> Add moat timeout monitoring

- src/js/utils/index.js
- src/js/utils/metrics.js
- test/qunit/metrics.test.js
- test/qunit/utils.test.js
This enables delegating metrics sampling to `o-ads` by adding a new configuration parameter to the metrics config array. 
It avoids having to replicate the sampling logic on every app that uses the `o-ads` metrics functionality. 
If the `sampleSize` parameter is not specified, `o-ads` will NOT sample and, therefore, will execute the callback every time a "trigger" event is dispatched.
> Add monitoring sampling functionality

- .circleci/config.yml
- docs/docs/developer-guide/advanced-display.md
The recently-added `snyk monitor` task is failing when it runs on the `npm publish` step in CircleCI.
As @taktran has found out, the reason for it seems to be the fact `npm publish` is expecting a `node_modules` to exist from a previous `npm install`. However, we don't seem to be using the `attach workspace` functionality that CircleCI provides in our `.circleci/.config.yml`. 
I cannot fix it quickly without having to spend quite some time learning more about CircleCI, so I've decided to open a new issue for that and mute the problem temporarily.
I am using this same PR to add some missing documentation for the `disableSampling` functionality in the metrics.
> Temporarily shut off snyk monitor

- src/js/ad-servers/gpt.js
`creativeId` is currently missing from the `slotRenderStart` event. This fixes it
> Fixed creativeId missing in slotRenderStart event

- .circleci/config.yml
Snyk should be able to run without node_modules, it just scans the package.json previous error was due to the fact that customer-products org is not setup with this repo
> add snyk report on test

- karma.conf.js
- package.json
- src/js/utils/metrics.js
- test/qunit/metrics.test.js
This adds the ability to track [built-in browser navigation time marks](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceNavigationTiming) from within `o-ads`. 
It's going to be useful to compare ads-loading performance with overall page-loading performance.
> Page perf metrics

- src/js/slot.js
- src/js/utils/events.js
- src/js/utils/index.js
- src/js/utils/metrics.js
- test/qunit/gpt.test.js
- test/qunit/utils.test.js
This adds the value of gpt's `isEmpty` attribute to any `slot` metrics where it's available (mostly useful in `slot-rendered`).
> Added "isEmpty" attribute from DFP's response to slot metrics

- package.json
The `release` task in `package.json` seems to fail on the very last step because it. I believe it has to do with a change in the `release-it` package that I hope this PR will fix.
> Attempt to fix broken release task

- .circleci/config.yml
- .release-it.json
- package.json
A change was needed in `release-it.json` after upgrading to the latest version, this was preventing the GitHub release from using the label that the CircleCI config was expecting to kick off publishing to npm.
> Adapted release-it config to latest version

- package.json
- src/js/utils/index.js
- src/js/utils/metrics.js
- test/qunit/metrics.test.js
This adds a new public method in `utils.clearPerfMarks` that allows to clear existing performance marks for certain event groups based on an existing metrics definitions array.
This allows removing performance marks for previously visited pages in environments where internal navigation is supported, like a web-app.
> Added new clearPerfMarks method to metrics utils

- package-lock.json
- package.json
Having a `homepage` field in `package.json` is useful as users can then run `npm home` from the `o-ads` repo and they will be sent to that url on their default browser.
Or they can run `npm home @financial-times/o-ads` from anywhere and get the same effect.
> Added missing homepage field to package.json

- .circleci/config.yml
The current `publish-to-npm` task in CircleCI [is broken](https://circleci.com/gh/Financial-Times/o-ads/2457)
> Run npm install before running occ upon publishing to npm

- src/js/utils/events.js
- src/js/utils/index.js
- src/js/utils/metrics.js
This adds a new `markPageChange` that enables creating performance marks for page navigation events and can clears old performance marks for previously visited pages.
> Add page change logic

- src/js/utils/metrics.js
This fixes the 'pageChange' event not being triggered, which makes it impossible to send metrics based on page changes
> Fix pageChange event not being triggered

- .eslintignore
- babel.config.js
- jest.config.js
- package-lock.json
- package.json
- src/js/utils/metrics.js
- test/jest/.eslintrc.json
- test/jest/metrics.js
- test/jest/pMark.js
- test/jest/testUtils/pMark.js
Page-level events, i.e. the ones fired with `utils.broadcast` unlike the ones fired via `slot.fire`, create a performance mark that doesn't contain a suffix in its name. 
However, those performance marks might be needed in a group that expects a suffix (e.g. the ones triggered by `slotGoRender` or `slotRenderEnded`).
This fixes a bug in which page-level marks are not being picked by slot-triggered actions.
> ADSDEV-95 Fix page change not being picked

- package-lock.json
- package.json
- src/js/slot.js
- src/js/slots.js
- test/.eslintrc.json
- test/jest/slot.js
- test/qunit/slots.post.message.test.js
This change makes `o-ads` react to a postMessage with a property `type` set to `oAds.slotClass` and a `slotClass` property set to an arbitrary value by adding a new class `data-o-ads-{arbitrary value}` to the slot container
> Enable class injection based on the new o-ads-embed postMessage

- README.md
- docs/docs/developer-guide/index.md
The links to the Google DFP (https://www.google.com/dfp) are erroring (https://www.google.com/intl/en_GB/dfp/info/welcome.html#error=no_adsense). Do you need an adsense account to view this link? Or is it just a broken link?
Either way perhaps this should be a public. Had a look and it seems to me a bit like Google have moved away from the 'Doubleclick for Publishers' product name and it's been wrapped up into Google Ad Manager (https://www.ezoic.com/what-is-google-ad-manager-what-happened-to-adx-adsense-dfp/). 
This PR adds what seemed to me like a good intro link but perhaps the team has a better alternative? https://support.google.com/admanager/answer/6022000?hl=en
Suggestions?
> New link for DFP / Google Ad Manager

- src/js/ad-servers/gpt.js
`next-ads-api` returns a boolean value for the `'loggedInStatus'`:
```
{
"name": "loggedInStatus",
"key": "loggedIn",
"value": true
}
```
This generates a silent error when setting the GPT targeting info here in `o-ads`:
Discussed with the team / stakeholders and agreed to remove the `loggedIn` value from the api as it's not used by the campaign management team however it is used by some other services e.g. https://github.com/Financial-Times/ft-creative-ss3/blob/d18b6fba5f4eb598bff3737afd0b06b70ab64bf8/themes/base/src/js/module/oPermutive.js#L15. Removing the value from the `next-ads-api` would break this dependency. 
Ensure that all values that are set as targeting with GPT are strings and thus correctly added to the URL. 
* I considered an if statement / ternary to check if the value is …
> Stringify all values passed in to GPT targeting

- main.scss
- secret-squirrel.js
This fixes the issue reported in our board (ADSDEV-131) in which GPT sets the width of an DOM element explicitly in an inline property causing the ads to align to the left rather than to the center.
> Added CSS rule to counter GPT broken CSS

- src/js/ad-servers/gpt.js
Exposes a new function to tell whether gpt has properly loaded, picked from [here](https://developers.google.com/doubleclick-gpt/common_implementation_mistakes).
It's currently useful for tracking on top of the `serverScriptLoaded` and `adServerLoadError` events.
> expose a new util function for gpt to tell whether it has loaded

- src/js/data-providers/api.js
- test/cypress/integration/ad-requests.test.js
- test/fixtures/content-api-response.json
- test/fixtures/user-api-response.json
- test/qunit/api.test.js
o-ads currently contains a module for passing data from an api-end-point into `o-ads config`. 
In o-ads v13 some of this functionality was removed as it has been decided that the `data-providers/api` module will be deprecated in a future release.
In the short term however we've found that some of the previously removed functionality is still useful on FT.com.
This PR re-instates some functionality for marshalling the ads-api data and passing it on to consuming apps.
> Backwards compatibilty v1 ads api

- .circleci/config.yml
- package.json
- prettier.config.js
- src/js/ad-servers/gpt.js
- src/js/utils/url.js
- test/jest/utils/url.js
- test/qunit/gpt.test.js
- test/qunit/targeting.test.js
Currently targeting requests include all parameters in the referring URL, including potentially sensitive information such as search terms
This PR adds a new utility method `stripUrlParams` which removes a configurable list of parameters from the main body of the URL and from named nested parameters.
Additional CI-related features:
- Performance: adding the ` --production` flag to `obt build` reduces the output from 105Kb to 13Kb
- Pre-commit tasks: `npx obt verify` has been added to prevent linting issues failing the build
- Code coverage: Karma is no longer part of the `test-unit` task to prevent coverage issues failing the build
Additional miscellaneous features
- Prettier config added to ensure conformance with code style coventions
> ADSDEV-350, stop search terms going into targeting

- renovate.json
This PR adds the recommended config for Renovate Bot to do its thing now that it has been added to the [list of installed apps](https://github.com/Financial-Times/o-ads/settings/installations)
> Add renovate bot to keep dependencies up to date

- src/js/ad-servers/gpt.js
The oAds.gpt.updatePageTargeting() function clears any targeting parameters previously set. This is a problem, because in the case of brandmetrics on the app, they are setting a parameter directly on the global window.googletag object, before we are calling updatePageTargeting() , and hence it removes it. My solution would be to not clear the targeting inside updatePageTargeting() but instead create a function clearPageTargeting() and call this explicitly wherever needed.
> Clear page targeting separately

- secret-squirrel.js
A code CODEOWNERS  has been recently added to this repo. However, that makes `git push` fail as secret-squirrel complains about that file. 
This fixes it similarly to what's been done in other places.
> Fix secret-squirrel complaining about CODEOWNERS

- src/js/data-providers/api.js
- test/qunit/api.test.js
This change enables adding additional `cust_params` by passing the api responses to an external method received in `o-ads`' configuration which can return an object whose key-value collection will be used for the additional targeting.
By using this approach API targeting marshalling can be done outside `o-ads` which has some benefits like de-coupling `o-ads` from app-specific logic, which allows us not to expose FT-specific logic in this repo (including feature flags, etc.. ).
It's worth noticing that:
1.  If `this.config.apiResponseHandler` doesn't contain a function, no new logic will be executed by `o-ads`
2. If `this.config.apiResponseHandler` returns `null` or `undefined`, no new logic will be executed by `o-ads` 
3. I have this working in conjunction with `n-ads` locally for …
> ADSDEV-394: Enable callback for additional targeting handling

- src/js/data-providers/api.js
- test/nightwatch/basic/individual-ad-lazy-load-margin.js
- test/nightwatch/page_objects/ad.js
A couple of nightwatch tests fail on MS Edge. I am not entirely sure why, but this fixes it.
The increase timeout also fixes some random failures due to some tests taking longer than expected.
> Fix nightwatch flakiness

- .circleci/config.yml
Currently cypress fails to run on CircleCI due to missing dependencies, I've added a run command to install all the dependencies Cypress requires.
> Install the dependencies required for cypress to work

- src/js/ad-servers/gpt.js
- src/js/slot.js
- test/jest/gpt.js
- test/jest/testUtils/pMark.js
- test/qunit/gpt.test.js
- test/qunit/setup.test.js
Noticed that when `enableLazyLoad` flag is not provided - meaning is not included in the gpt's options passed to o-ads - the routine `gpt.enableLazyLoad` is executed anyway.
This causes `gpt.enableLazyLoad` to warn the user that the config object is not compliant - as it expects either an object or a boolean.
`gpt.enableLazyLoad` is not executed if the flag is not provided.
> ADSDEV-469 Do not run gpt's enableLazyLoad routine when flag not provided

- README.md
Links to instructions on how to include Origami components:
https://github.com/Financial-Times/origami/issues/59
Avoids repeating generic component usage information:
https://origami.ft.com/spec/v1/components/#readme
Corrects heading levels.
> Update general usage in readme

- .circleci/config.yml
Because why not?
Just kidding.
After discussion with Andrew, we agreed that cypress and pupeteer tests are doing the same thing as what is now tested with titella. These tests were also not as accurate as titella, as they are testing demo pages which can get out of date and are not as accurate as testing the live site. Testing is dead. Long live testing (through titella)
Also removing nightwatch tests, as we agreed these don't add much value (we are just rendering a couple of divs!). o-ads is going into maintenance mode. The tests currently pass and we are not making any more active changes to the repo. Similarly the nightwatch config uses fixed versions for browsers so it will not catch any errors on new browser releases (which is also very unlikely).
The tests haven't been removed so …
> Remove nightwatch, cypress and pupeteer tests

- .github/workflows/auto-approve.yml
We have workflows that currently fail to run correctly for pull-requests from forks or pull-requests from dependabot. The reason is because those workflows are being triggered by the 'pull_request' event, which does will use a restricted github api token for pull-requests from forks or dependabot for security reasons.
For our workflows which are 'safe' (meaning they do not checkout the code or execute the code in the repository), we can change their trigger from 'pull_request' to 'pull_request_target', which uses a github api token with more permissions, specifically it has permission to read/use secrets, which are the things are workflows require.
Our workflows are safe, they do not checkout or execute the code from the repository, so we should change to using `pull_request_target` to …
> use pull_request_target and not pull_request for the safe workflows
